//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avaliacao.Gama.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvaliacaoEstudanteResposta
    {
        public int AvaliacaoEstudanteRespostaID { get; set; }
        public int AvaliacaoEstudanteID { get; set; }
        public int QuestaoAlternativaID { get; set; }
        public System.DateTime DataRegistro { get; set; }
    
        public virtual AvaliacaoEstudante AvaliacaoEstudante { get; set; }
        public virtual QuestaoAlternativa QuestaoAlternativa { get; set; }
    }
}
