//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avaliacao.Gama.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avaliacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avaliacao()
        {
            this.AvaliacaoEstudante = new HashSet<AvaliacaoEstudante>();
        }
    
        public int AvaliacaoID { get; set; }
        public string AvaliacaoNome { get; set; }
        public int DocenteID { get; set; }
        public int QuestionarioID { get; set; }
        public System.DateTime DataRegistro { get; set; }
    
        public virtual Docente Docente { get; set; }
        public virtual Questionario Questionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvaliacaoEstudante> AvaliacaoEstudante { get; set; }
    }
}
