//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avaliacao.Gama.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvaliacaoEstudante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AvaliacaoEstudante()
        {
            this.AvaliacaoEstudanteResposta = new HashSet<AvaliacaoEstudanteResposta>();
            this.AvaliacaoResultadoEstudante = new HashSet<AvaliacaoResultadoEstudante>();
        }
    
        public int AvaliacaoEstudanteID { get; set; }
        public int AvaliacaoID { get; set; }
        public int EstudanteID { get; set; }
        public Nullable<System.DateTime> DataInicio { get; set; }
        public Nullable<System.DateTime> DataFim { get; set; }
    
        public virtual Avaliacao Avaliacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvaliacaoEstudanteResposta> AvaliacaoEstudanteResposta { get; set; }
        public virtual Estudante Estudante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvaliacaoResultadoEstudante> AvaliacaoResultadoEstudante { get; set; }
    }
}
