//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avaliacao.Gama.Api
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class modelEntities : DbContext
    {
        public modelEntities()
            : base("name=modelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avaliacao> Avaliacao { get; set; }
        public virtual DbSet<AvaliacaoEstudante> AvaliacaoEstudante { get; set; }
        public virtual DbSet<AvaliacaoEstudanteResposta> AvaliacaoEstudanteResposta { get; set; }
        public virtual DbSet<AvaliacaoResultadoEstudante> AvaliacaoResultadoEstudante { get; set; }
        public virtual DbSet<Docente> Docente { get; set; }
        public virtual DbSet<Estudante> Estudante { get; set; }
        public virtual DbSet<Questao> Questao { get; set; }
        public virtual DbSet<QuestaoAlternativa> QuestaoAlternativa { get; set; }
        public virtual DbSet<Questionario> Questionario { get; set; }
        public virtual DbSet<QuestionarioQuestao> QuestionarioQuestao { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
