//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avaliacao.Gama.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionarioQuestao
    {
        public int QuestionarioQuestaoID { get; set; }
        public Nullable<int> QuestionarioID { get; set; }
        public Nullable<int> QuestaoID { get; set; }
        public Nullable<short> Sequencia { get; set; }
        public int CriadoPor { get; set; }
        public System.DateTime DataRegistro { get; set; }
    
        public virtual Docente Docente { get; set; }
        public virtual Questao Questao { get; set; }
        public virtual Questionario Questionario { get; set; }
    }
}
