//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avaliacao.Gama.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestaoAlternativa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestaoAlternativa()
        {
            this.AvaliacaoEstudanteResposta = new HashSet<AvaliacaoEstudanteResposta>();
        }
    
        public int QuestaoAlternativaID { get; set; }
        public string QuestaoAlternativaTexto { get; set; }
        public Nullable<bool> Correto { get; set; }
        public int QuestaoID { get; set; }
        public int CriadoPor { get; set; }
        public System.DateTime DataRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvaliacaoEstudanteResposta> AvaliacaoEstudanteResposta { get; set; }
        public virtual Docente Docente { get; set; }
        public virtual Questao Questao { get; set; }
    }
}
